/camera_pointcloud_to_scan:
  ros__parameters:
    angle_increment: 0.0087
    angle_max: 1.57        
    angle_min: -1.57
    range_max: 10.0
    range_min: 0.2
    max_height: 1.0
    min_height: 0.05
    target_frame: base_footprint
    use_inf: true

    remap_cloud_in_source: "/cloud_in"
    remap_cloud_in_target: "/hsrb/head_rgbd_sensor/depth_registered/points"
    remap_scan_out_source: "scan"
    remap_scan_out_target: "/hsrb/camera_scan"

    qos_overrides:
      /hsrb/head_rgbd_sensor/depth_registered/points:
        subscription:
          depth: 1
          reliability: "best_effort"
          durability: "volatile"
      /camera_scan:
        publisher:
          depth: 1
          reliability: "best_effort"
          durability: "volatile"

/ros2_laser_scan_merger:
  ros__parameters:
    pointCloudTopic: /cloud_in
    pointCloudFrameId: base_footprint
    scanTopic1: /hsrb/base_scan 
    scanTopic2: /hsrb/camera_scan
    show1: true
    show2: true

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.0087
    angle_max: 3.14
    angle_min: -3.14
    range_max: 10.0
    range_min: 0.35
    scan_time: 0.3333
    max_height: 1.0
    min_height: 0.0
    target_frame: base_footprint
    transform_tolerance: 0.01
    use_inf: true
    remap_scan_out_source: "scan"
    remap_scan_out_target: "/hsrb/merged_scan"